my:
  server:
    addr: 127.0.0.1
#    ${my.server.addr}
spring:
  datasource:
    url: jdbc:mysql://${my.server.addr}:3306/mall_seckill?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: always
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:ㄤ
        server-addr: ${my.server.addr}:8848
    sentinel:
      transport:
        port: 8870
        dashboard: 127.0.0.1:8080
  redis:
    host: 43.143.128.214 #從本地${my.server.addr}  改成雲主機位置才能使用到布隆過濾器腳本 也就是lua的腳本
    port: 6379 #跟老師不一樣端口，否則服務器撐不住
    password:
  rabbitmq:
    host: ${my.server.addr}
    port: 5672
    username: guest
    password: guest
    virtual-host: /


dubbo:
  application:
    name: mall-seckill
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:8848
    use-as-metadata-center: false
    use-as-config-center: false
  consumer:
    check: false
logging:
  level:
    cn.tedu.mall: trace